--- 
abstract: Postfix (MTA) text attribute communication
author: 
  - Hans Dieter Pearcey <hdp@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: POE-Filter-Postfix
requires: {}

version: 0.001
